### ISSUE TITLE
Field name got formatted, but no @map is generated

### ISSUE THREAD

**Issue by tuanalumi** [iiian/prisma-case-format#1]
Field name got formatted, but no `@map` is generated
Original
```
article_id Int
```

Expected to be converted to
```
articleId Int @map("article_id")
```

Actual result
```
articleId Int
```

**Comment by iiian** [comment]
Hey @tuanalumi! Thanks for pointing this out. [fix: repair map annotation drops](https://github.com/iiian/prisma-case-format/pull/2) has been merged, and v1.0.4 has been pushed out. Sorry for the late response on this.
