### ISSUE TITLE
Plural names for array fields

### ISSUE THREAD

**Issue by ozum** [iiian/prisma-case-format#10]
Hi,

Is it possible to format array fields as plural names?

Kind regards,

**Comment by iiian** [comment]
Hi @ozum! It is currently not possible to do this with `prisma-case-format`. My gut (which may be wrong) is that this feature is a little bit out of scope.

Are you currently facing a situation where you have a large number (more than a dozen) of fields that are array types?

**Comment by ozum** [comment]
Hi @iiian. I mean one to many relations. They are array fields and I have hundreds of them. Below is just one example model. All foreign key fields are array.

Having plurals for array fields would be much more intuitive.

```ts
model Business {
  id                 String               @id(map: "BusinessId") @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  languageCode       String               @db.Char(2)
  currencyCode       String               @db.Char(3)
  createdAt          DateTime             @default(now()) @db.Timestamptz(0)
  name               String               @db.VarChar(64)
  languages          String[]             @default([]) @db.Char(2)
  phone              String               @db.VarChar(15)
  address            String?              @db.VarChar(250)
  billingName        String?              @db.VarChar(64)
  billingAddress     String?              @db.VarChar(250)
  taxOffice          String?              @db.VarChar(64)
  taxId              String?              @db.VarChar(64)
  defaultTaxRate     Decimal?             @db.Decimal(8, 6)
  isActive           Boolean              @default(true)
  batchOperation     BatchOperation[]
  currency           Currency             @relation(fields: [currencyCode], references: [code], onUpdate: Restrict, map: "BusinessCurrency")
  language           Language             @relation(fields: [languageCode], references: [code], onUpdate: Restrict, map: "BusinessLanguage")
  ingredientCategory IngredientCategory[]
  itemCategory       ItemCategory[]
  optionCategory     OptionCategory[]
  profile            Profile[]
  recipe             Recipe[]
  tab                Tab[]
  targetGroup        TargetGroup[]

  @@schema("public")
}

```

**Comment by iiian** [comment]
@ozum I see. While this is probably better raised with the prisma team itself, I get how getting small features fulfilled with them at this point is probably like pulling teeth because it's large.

I can add a dep for `pluralize`

**Comment by iiian** [comment]
v1.2.0 released with `-p` flag to support this

**Comment by ozum** [comment]
>  I get how getting small features fulfilled with them at this point is probably like pulling teeth because it's large project with a scheduled roadmap.

Exactly :). For the same reasons, I developed [vuepress-bar](https://github.com/ozum/vuepress-bar). I prefer it was built-in.

> v1.2.0 released with -p flag to support this

Thanks for fast response.
