### ISSUE TITLE
enum definitions do not stay PascalCase when running 'prisma db pull'

### ISSUE THREAD

**Issue by fullstackzach** [iiian/prisma-case-format#17]
Hello, thanks for creating this awesome cli utility! 

I tried applying it to a prisma schema and noticed enums are made PascalCase, however the next time I run `npx prisma db pull`, those enums are reverted to `snake_case`. A workaround that works is to run this utility following each time we introspect.

Our workflow is database-first using the instrospection workflow, so we make migrations separately in SQL and pull those changes into the prisma schema, so we run `prisma db pull` often.

I think having this util add `@@map('enum_name')` will cause the enum naming to stick as PascalCase when running `prisma db pull`

**Comment by iiian** [comment]
Hey Zach, I'm glad it's of some value! 

I think `@@map('enum_name')` makes sense too, and I was debating inserting it at one point because it wasn't quite compulsory. For my testing purposes, how are you using the command? Are you using `--map-table-case` at all?

**Comment by fullstackzach** [comment]
a followup thought, since renaming enums isn't compulsory, should prisma-case-format leave them alone? And/or provide another CLI option to provide a mapping directive? e.g. something like `--map-enum-case PascalCase`

**Comment by iiian** [comment]
> a followup thought, since renaming enums isn't compulsory, should prisma-case-format leave them alone? And/or provide another CLI option to provide a mapping directive and use `@@map` too? e.g. something like `--map-enum-case PascalCase`

Could be. I may have more time to look into this issue this weekend or next, will keep you posted once I can immerse my head back in this project

**Comment by shellscape** [comment]
Another big thanks for putting this together, and another vote for enum handling.

**Comment by iiian** [comment]
@fullstackzach, I plan to house the behavior of a flag like `--map-enum-case` under `--map-table-case`. I don't think it will hurt for the tool to start outputting `@@map` on all of the schemas for either db-first or model-first. Similarly, I think that for the time-being, I would think people want to have their `model`s `view`s and `enum`s all have the same case convention, which is controlled by `--map-table-case`. But who knows!

**Comment by iiian** [comment]
I've released `v1.4.0-beta.1` implementing this feature, if you could pull that version, give it a quick spin and see how it works, that would be appreciated!

https://www.npmjs.com/package/prisma-case-format

**Comment by fullstackzach** [comment]
Hey @iiian - sorry for the late response here, got caught up with other things. I am using the new version and it is working great, thanks for your efforts!
