### ISSUE TITLE
Doesn't map after first table

### ISSUE THREAD

**Issue by shellscape** [iiian/prisma-case-format#18]
Running the tool with `prisma-case-format --file prisma/schema.prisma --pluralize` it doesn't map after the first table. Here's the source prisma schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "../node_modules/@generated/read"
  previewFeatures = ["views"]
}

generator typegraphql {
  provider = "typegraphql-prisma"
}

datasource db {
  provider = "postgres"
  url      = env("DB_URL")
}

model goose_db_version {
  id         Int       @id @default(autoincrement())
  version_id BigInt
  is_applied Boolean
  tstamp     DateTime? @default(now()) @db.Timestamp(6)
}

view accounts {
  id         String    @unique @db.Uuid
  created_at DateTime? @db.Timestamp(6)
  name       String?
  updated_at DateTime? @db.Timestamp(6)
  owned_by   String?   @db.Uuid
  users      users?
}
```

And the result of a dry run (which also matches running normally)

```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "../node_modules/@generated/read"
  previewFeatures = ["views"]
}

generator typegraphql {
  provider = "typegraphql-prisma"
}

datasource db {
  provider = "postgres"
  url      = env("DB_URL")
}

model GooseDbVersion {
  id        Int       @id @default(autoincrement())
  versionId BigInt    @map("version_id")
  isApplied Boolean   @map("is_applied")
  tstamp    DateTime? @default(now()) @db.Timestamp(6)

  @@map("goose_db_version")
}

view accounts {
id         String    @unique @db.Uuid
created_at DateTime? @db.Timestamp(6)
name       String?
updated_at DateTime? @db.Timestamp(6)
owned_by   String?   @db.Uuid
users      users?
}
```

You can see from the output above that after `goose_db_version` the tool ceases to convert.

**Comment by iiian** [comment]
Hey @shellscape. IIRC `views` are a relatively new feature in Prisma, so this tool doesn't support them yet. It looks like there are mounting feature requests so I'm trying to take care of them this weekend. Will keep you posted.

**Comment by shellscape** [comment]
Thanks for the quick reply. If you don't have the opportunity I'll probably be able to get add that capability this next week.

**Comment by iiian** [comment]
@shellscape, if you take a look at https://github.com/iiian/prisma-case-format/pull/20/files#diff-390b3178f6c849ab73dd0194ed9c880eb7073d0f00ea0f872cd0f3c2af6513f8R592, does this jest snapshot match your expectations for the output based on the example schema you provided?

**Comment by iiian** [comment]
I think the only thing of concern would be the `usersId` being created randomly by the schema formatter. Although technically the example schema that I plugged in was invalid because `users` on `view accounts` doesn't have an associated id to build an fk. I'm sure if we plugged one in, everything would be fine.

**Comment by iiian** [comment]
Also, I think `Accounts Accounts[]` on the `Users` is getting dropped their by the `formatSchema` operation as well. If those pieces were in place in the source schema, as required, the tool would behave properly. Probably not a great idea to test on a schema w/ errors, I'll get that fixed.

**Comment by shellscape** [comment]
Yeah that looks about right to me.

**Comment by iiian** [comment]
I've released `v1.4.0-beta.0` https://www.npmjs.com/package/prisma-case-format/v/1.4.0-beta.0?activeTab=readme. Please give it a shot and let me know how it works out for you!

**Comment by shellscape** [comment]
Much appreciated. Will do my best to try it tonight

**Comment by shellscape** [comment]
Just gave it a try and it looks _beautiful_. Thanks for getting that in.
