### ISSUE TITLE
Exclude the next code from fomatting.

### ISSUE THREAD

**Issue by yoshimaru46** [iiian/prisma-case-format#19]
@iiian 
Thanks for creating this awesome CLI utility!

It would be great if you could add the ability to skip the format of a line with a specific comment! 
(ex. like prettier's `// prettier-ignore` comment. https://prettier.io/docs/en/ignore.html

If there are no problems, I will create a PR!

**Comment by iiian** [comment]
Please do!

**Comment by ebramanti** [comment]
Was this ever implemented? Use case I have is that some of our tables in our DB are not properly pluralized and the output I get is now mapping improperly.

**Comment by iiian** [comment]
@ebramanti, unfortunately I can't completely discern your issue from your description. Feel free to leave a more detailed description (with examples: input, expectation, actual) either on this ticket or on a separate one. Thanks!
