### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'groups')

### ISSUE THREAD

**Issue by gajus** [iiian/prisma-case-format#23]
Not clear what this error refers to, but it does not format the file.

**Comment by ahto** [comment]
i hit this too. i have a big db but this small piece still gives the same error.
if i remove the `view_count` it works after that.

```
generator client {
  provider        = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model some_table {
  id                        Int       @id @default(autoincrement()) @db.MediumInt
  view_count                Int?      @default(0)
}
```

**Comment by ahto** [comment]
I made one fix suggestion. But feel free to reject if it was too simple fix. At least the test should help a bit.
https://github.com/iiian/prisma-case-format/pull/24

**Comment by iiian** [comment]
v1.4.1 released. Thanks a bunch for fixing this @ahto
