### ISSUE TITLE
Pluralize table names

### ISSUE THREAD

**Issue by maxfurman** [iiian/prisma-case-format#25]
Hi, thanks for making this handy utility! I'm working on something connecting to an existing postgres db with Prisma, and the convention used is plural table names. So what I'd like is an option to pluralize table names, so that the following prisma schema

```
model User {
  id @id @default(autoincrement())
}
```
is converted to
```
model User {
  id @id @default(autoincrement())
  
  @@map("users")
}
```
instead of the existing behavior
```
model User {
  id @id @default(autoincrement())

  @@map("user")
}
```
Is this possible? Thanks again!

**Comment by iiian** [comment]
Hey @maxfurman, glad you found it helpful. I totally get where you're coming from, somebody made the table plural, that's weird, you want it to be singular. Probably doable, can it wait til the weekend?

**Comment by maxfurman** [comment]
Thanks for the quick response, @iiian . I think there's a misunderstanding, I want the table names to be plural, so that the sql looks like `select * from users;`. So in combination with `--map-table-case snake`, a prisma `model ShoppingCart` gets `@@map("shopping_carts")`

**Comment by iiian** [comment]
> Thanks for the quick response, @iiian . I think there's a misunderstanding, I want the table names to be plural, so that the sql looks like `select * from users;`. So in combination with `--map-table-case snake`, a prisma `model ShoppingCart` gets `@@map("shopping_carts")` 

Whoop, nope I simply miscommunicated. Meant to say somebody named the table plurally, you want to reference it singularly in code, like sane people.

**Comment by iiian** [comment]
Proposed interface: I'm thinking about `--map-table-case=snake,plural` as the interface for supporting this, where `plural` is a new optional argument to signal that database targets should be pluralized. Alternatively, if you're in a scenario where you need to surgically target only a number of databases for renaming, the argument input could be extended to declare tablewise overrides to the rule:


`--map-table-case=snake|User:users|Group:pigeons`

where `User:users` specifies that `model User` shall have `@@map("users")` and `Group:pigeons` specifies that `model Group` shall have `@@map("pigeons")`. The `|` in between shall be separators for mapping override instances.

If you don't need the latter extension for tablewise overrides, I'll just add the `--map-table-case=snake,plural` flavor for now.

**Comment by iiian** [comment]
v1.5.0 has been released and should address this issue.

**Comment by ebramanti** [comment]
Is it possible to go from plural to singular on the field case? For example:
```
model Users {
  id @id @default(autoincrement())

  @@map("users")
}
```
to
```
model User {
  id @id @default(autoincrement())

  @@map("users")
}
```

**Comment by iiian** [comment]
> Is it possible to go from plural to singular on the field case? For example:
> 
> ```
> model Users {
>   id @id @default(autoincrement())
> 
>   @@map("users")
> }
> ```
> 
> to
> 
> ```
> model User {
>   id @id @default(autoincrement())
> 
>   @@map("users")
> }
> ```

@ebramanti that's a fair request. I've updated w/ `v1.6.0` s.t. you can do

```
prisma-case-format --table-case=pascal,singular
```

Which will have the effect of performing the specified transformation.
