### ISSUE TITLE
Some `@@index` cannot be converted

### ISSUE THREAD

**Issue by u3u** [iiian/prisma-case-format#26]
Input

```prisma
@@index([test_field(length: 191)], map: "test_field_index")
```

Should be converted to

```prisma
@@index([testField(length: 191)], map: "test_field_index")
```

**Comment by iiian** [comment]
@u3u thanks for reaching out. These should be some fairly straight forward regex updates for `prisma-case-format`, and also thank you for alerting me that `@@index` annotations may be more complex than I previously anticipated.

**Comment by iiian** [comment]
@u3u , I've released https://www.npmjs.com/package/prisma-case-format/v/1.7.0-beta.0.

Please pull it down, give it a crank, and let me know if it fixes your issue!

**Comment by u3u** [comment]
Thank you for your great work! There are no issues in my use case. 🥳

**Comment by iiian** [comment]
awesome, `v1.7.0` released.
