### ISSUE TITLE
`Unsupported` fields are parsed incorrectly

### ISSUE THREAD

**Issue by ebramanti** [iiian/prisma-case-format#30]
Prisma will sometimes represent columns as `Unsupported` if the data type can not be matched up to a Prisma type. Reference here: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#unsupported

Unsupported can optionally include the name of the unsupported type with this syntax:
```prisma
model Star {
  id           Int                    @id @default(autoincrement())
  circle_value Unsupported("circle")?
}
```
However, using the `--map-table-case` option with an annotated Unsupported value (`("circle")`) results in output like this:
```prisma
model Star {
  id Int @id @default(autoincrement())
  circleValue Unsupported @map("circle_value")("circle")?

  @@map("stars")
}
```

Command I am running:
```
npx prisma-case-format --map-table-case=snake,plural
```

**Comment by ebramanti** [comment]
I created a regression test here: https://github.com/ebramanti/prisma-case-format/commit/9e82bc0825cc5534648d25cd2a92431eecfc19fc

From what I can tell, a change needs to be made to the `FIELD_DECLARATION_REGEX`. Not sure if this needs to be `Unsupported`-specific or more generalized for all fields.

**Comment by iiian** [comment]
Awesome, thanks @ebramanti . I should be able to take a look at this this weekend.

**Comment by iiian** [comment]
@ebramanti just for clarification on the mechanics of `Unsupported` fields, as they're quite new to me, the desired output here is:

```prisma
circleValue Unsupported("circle")? @map("circle_value")
```

correct?

**Comment by iiian** [comment]
Assuming this is correct, `prisma-case-format@1.7.1-beta.0` is available for download: https://www.npmjs.com/package/prisma-case-format/v/1.7.1-beta.0

**Comment by ebramanti** [comment]
> @ebramanti just for clarification on the mechanics of `Unsupported` fields, as they're quite new to me, the desired output here is:
> 
> ```prisma
> circleValue Unsupported("circle")? @map("circle_value")
> ```
> 
> correct?
Yes, this is the behavior that should be occurring. 

Aside from the bin script not having proper permissions on `prisma-case-format@1.7.1-beta.0` (had to run `chmod +x node_modules/.bin/prisma-case-format`), the conversion now works and produces a valid Prisma schema. Thanks!
