### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by mhchen** [iiian/prisma-case-format#36]
Love the tool, but concerned about using it with no `LICENSE` file in the root. You do specify `license: "ISC"` in `package.json` but would feel better with a LICENSE in the repo. Would be grateful if you added it

Here's the text of the ISC license 

```
Copyright <YEAR> <OWNER>

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

**Comment by iiian** [comment]
Thanks, Mike. Do you care if it gets published with a new version of the NPM package, or is presence in the repo sufficient?

**Comment by iiian** [comment]
`LICENSE` file included at your suggestion.

**Comment by mhchen** [comment]
Thank you @iiian! Not a lawyer but pretty sure its presence in the repo will do the trick

really appreciate it!

**Comment by iiian** [comment]
No problem!
