### ISSUE TITLE
Any way to keep enums singular when table names are plural?

### ISSUE THREAD

**Issue by kolpakov-p** [iiian/prisma-case-format#39]
Hey!

I have the following schema:

```
model ConfirmRequest {
  type        ConfirmType @map("type")
  ...

  @@map("confirm_requests")
}

enum ConfirmType {
  EMAIL
  PHONE

  @@map("confirm_type")
}
```

And I'm running CLI tool as follows:
` prisma-case-format --file ./prisma/schema.prisma --map-table-case snake,plural`

So, I need to keep `enum` `@@map` singular. Do we have any way to achieve that?

In other words, I need to manage `enum` transform options separately from table ones.

Thanks for great tool!

**Comment by iiian** [comment]
I think we ended up managing table & enum case simultaneously, so at this point it's "because legacy".

we could probably add `--map-enum-case` to run things separately, I just need to make sure that doesn't break backwards compat

**Comment by kolpakov-p** [comment]
That would be great!

Do you have time to do this in 1-2 weeks, or will my help be needed?

**Comment by iiian** [comment]
I'd **love** your help! I'm swamped at work this week with some new production rollouts.

If you decide to just implement `--map-enum-case` without preserving backwards compat that's perfectly fine, we'll just trip a 2.0 version bc there are some people using this in production CI/CD systems.

red-green TDD works pretty well in this repo, haven't had any complaints yet. I think the pattern for test cases is pretty easy to repeat, but let me know if it looks weird. Also, I'm happy to provide some directions on what I think needs to be updated, but my gut feeling is that it'll look pretty clear after a bit.

Oh, and I think both `yarn` and `pnpm` work, if you don't want to use `npm`.
