### ISSUE TITLE
New version of package have old content

### ISSUE THREAD

**Issue by kolpakov-p** [iiian/prisma-case-format#43]
Somehow, I'm receiving the package ver. `2.0.0`, but with old content inside.

`yarn add prisma-case-format`

Yarn cache is purged.

![image](https://github.com/iiian/prisma-case-format/assets/10197692/2a032007-b4a8-4328-9337-b2600160072b)

**Comment by iiian** [comment]
Hey, yep, saw that,  fixed now. released `2.0.1` and deprecated `2.0.0`.
