### ISSUE TITLE
Q. How to use this tool ?

### ISSUE THREAD

**Issue by sacru2red** [iiian/prisma-case-format#48]
![image](https://github.com/iiian/prisma-case-format/assets/43224844/8833e0c4-422a-474c-91a7-a7480bd6809a)

It's not working.
Did I do something wrong?

**Comment by iiian** [comment]
Hey @sacru2red . Looks like you're using the beta version of 2.1.0. You've got two options here, roll back to ~2.0.0 or ^1.0.0,

Orrrr if you're feeling really generous, you could describe your schema/issue in greater detail because you've managed to find a bug I couldn't create

**Comment by sacru2red** [comment]
> Hey @sacru2red . Looks like you're using the beta version of 2.1.0. You've got two options here, roll back to ~2.0.0 or ^1.0.0,
> 
> Orrrr if you're feeling really generous, you could describe your schema/issue/usage in greater detail because you've managed to find a bug I couldn't create during my testing.

Thanks,
I try prisma-case-format@2.0.2. It seems to work

btw, I think prisma-case-format@2.0.2 must have "latest" tag
prisma-case-format@2.1.0-beta.0 must have "beta" tag in npm

**Comment by iiian** [comment]
Got it, yeah that could save me some problems. So could you describing your set up 😉

**Comment by sacru2red** [comment]
@iiian 
I Found it

this model makes ploblem

```
model sessions {
  session_id String  @id @localContainer.VarChar(128)
  expires    Int     @localContainer.UnsignedInt
  data       String? @localContainer.Text
}
```

**Comment by sacru2red** [comment]
so, It has been confirmed that model names ending in "s" are problematic.

**Comment by iiian** [comment]
Thanks for the update @sacru2red, your investigation will be helpful to me. I'll try and dig into this at my earliest availability.

**Comment by iiian** [comment]
@sacru2red could you please and thanks share how you're invoking `prisma-case-format`? I copied your schema in as a unit test and it seems to run just fine.

Thanks!

**Comment by sacru2red** [comment]
hey. I test on 2.1.0-beta.0
check https://github.com/sacru2red/prisma-case-format-issue

I think this library must check npm tags.
why "[2.1.0](https://www.npmjs.com/package/prisma-case-format/v/2.1.0)" doesnt have "latest" tag.
[2.0.2](https://www.npmjs.com/package/prisma-case-format/v/2.0.2) has "latest" tag
It looks strange.

check it 
[https://docs.npmjs.com/cli/v10/commands/npm-dist-tag](npm-dist-tag)

but I recommand use [release-it cli](https://www.npmjs.com/package/release-it)

> > Hey @sacru2red . Looks like you're using the beta version of 2.1.0. You've got two options here, roll back to ~2.0.0 or ^1.0.0,
> > Orrrr if you're feeling really generous, you could describe your schema/issue/usage in greater detail because you've managed to find a bug I couldn't create during my testing.
> 
> Thanks, I try prisma-case-format@2.0.2. It seems to work
> 
> btw, I think prisma-case-format@2.0.2 must have "latest" tag prisma-case-format@2.1.0-beta.0 must have "beta" tag in npm
